housejobs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', include('jobs.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    
]

jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('payments/', views.payments, name='payments'),
    path('reset/', views.reset_password, name='reset'),
    path('register/', views.register, name='register'),
    path('register/', views.register, name='add_user'),
    path('mark_done/', views.mark_done, name='mark_done'),
    path('review_done/', views.review_done, name='review_done'),
    path('mark_not_done/', views.mark_done, name='mark_not_done'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('new_job/', views.new_job, name='new_job'),
    path('<int:pk>/repost_job/', views.repost_job, name='repost_job'),
    path('<int:pk>/delete_job/', views.delete_job, name='delete_job'),
    path('job_payments/', views.job_payments, name='job_payments'),
]

jobs/models.py
from django.db import models
from django.db.models.deletion import CASCADE
import datetime
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class Payments(models.Model):
    # jobpost = models.ForeignKey(JobPost, on_delete=CASCADE)
    # payment_for_month = models.CharField(max_length=200)
    payment_amount = models.IntegerField(default=0)
    payment_date = models.DateTimeField('payment date', auto_now_add=True)
    payment_note = models.CharField(max_length=200, default=None)
    payment_uid = models.CharField(max_length=200, default=None)

    # def __str__(self):
    #     return str(self.id)

class JobPost(models.Model):
    job_title = models.CharField(max_length=200)
    publish_date = models.DateTimeField('date published', auto_now_add=True)
    job_is_template = models.BooleanField(default=False)
    job_detail = models.CharField(max_length=200)
    job_price = models.IntegerField(default=0)
    job_taken = models.BooleanField(default=False)
    job_under_review = models.BooleanField(default=False)
    job_passed_review = models.BooleanField(default=False)
    job_taken_date = models.DateTimeField('date job taken', null=True, blank=True)
    job_done = models.BooleanField(default=False)
    job_done_date = models.DateTimeField('date job completed', null=True, blank=True)
    job_taker = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='job_user')
    job_creator = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='job_author')
    job_rejected_by_admin = models.BooleanField(default=False)
    job_expired = models.BooleanField(default=False)
    job_paid = models.BooleanField(default=False)
    job_payment_id = models.ForeignKey(Payments, on_delete=models.CASCADE, null=True, blank=True, related_name='job_payment_id')
    
    def __str__(self):
        return self.job_title
    
    def was_published_recently(self):
        return self.publish_date >= timezone.now() - timezone.timedelta(days=1)

jobs/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import JobPost

class NewJob(forms.ModelForm):

    class Meta:
        model = JobPost
        fields = ('job_title','job_detail', 'job_price', 'job_creator')

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')
    
    def save(self, commit = True):
        print("save called from anonymous")
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.is_staff = True
        if commit:
            user.save()
        return user


class NewChildUserForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2')

    def save(self, parnt, commit = True):
        print("save called from admin", parnt)
        user = super(NewChildUserForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        
        if commit:
            user.save()
            user.groups.add(parnt)
        return user

jobs/views.py
from datetime import datetime
import time
from django.http import HttpResponseRedirect, HttpResponse
# from django.http.request import HttpRequest
from django.template import loader
from django.shortcuts import render, get_object_or_404
# from django.urls import reverse
# from django.views import generic
from .models import JobPost, Payments
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, Group
from django.utils import timezone
from django.db.models import Avg, Count, Min, Sum
import matplotlib.pyplot as plt
from io import StringIO
import numpy as np
from .forms import NewChildUserForm, NewJob
from django.shortcuts import redirect
import random

from .forms import NewUserForm
from django.contrib.auth import login
from django.contrib import messages


my_money_under_review_this_month = None
my_total_this_mont = None
unclaimed = None

def get_this_family_jobs(request):
    family_admin = None
    date_today = timezone.datetime.now()
    user_group = Group.objects.get(user = request.user)
    users_in_a_group = User.objects.filter(groups=user_group)
    for u in users_in_a_group:
        if u.is_staff:
            family_admin = u
    this_family_jobs = JobPost.objects.filter(job_creator=family_admin)
    return this_family_jobs


# Create your views here.
@login_required
def index(request):
    print("index - user is : ",request.user)
    user = User.objects.get(username = request.user)
    grps = request.user.groups.all()
    if len(grps) == 0:
        print("index - this user has no group")
        new_group = Group(name = request.user)
        new_group.save()
        user.groups.add(new_group)
    else:
        print("index - this user belongs to group", grps)
    user_group = Group.objects.get(user = request.user)
    print('user_group \n', user_group)
    
    users_in_a_group = User.objects.filter(groups=user_group)
    print('users in group \n',users_in_a_group )
    def job_creators(users_in_a_group):
        poster = None
        for u in users_in_a_group:
            job_list_1 = JobPost.objects.filter(job_creator = u).order_by('-id') 
            print (u, job_list_1, len(job_list_1))
            if len(job_list_1) > 0:
                print("job creator is", u.id)
                poster = u
                print(u)
                
            else:
                print('None')

        return poster
    date_today = timezone.datetime.now()            
    # print('current month :' , timezone.datetime.now().month)
    # print("Jobs on a specific date : ", JobPost.objects.filter(publish_date__month=date_today.month))
    this_family_jobs = JobPost.objects.filter(publish_date__month=date_today.month).filter(job_creator=job_creators(users_in_a_group))
    this_family_jobs_today = JobPost.objects.filter(publish_date__day=date_today.day).filter(job_creator=job_creators(users_in_a_group))
    
    print('this_family_jobs : ', this_family_jobs)
    
    if request.user.is_staff:
        print("I am a staff")
        my_jobs_under_review = this_family_jobs.filter(job_taker=user).filter(job_taken= True).filter(job_under_review= True).order_by('-id') 
        my_jobs_acceptably_done = this_family_jobs.filter(job_taker=user).filter(job_taken=True).filter(job_done=True).filter(job_passed_review= True).order_by('-id')
        
        jobs_under_review = this_family_jobs.filter(job_taken= True).filter(job_under_review= True).order_by('-id') 
        jobs_acceptably_done = this_family_jobs.filter(job_taken=True).filter(job_done=True).filter(job_passed_review= True).filter(job_paid=False).order_by('-id')
        jobs_review_rejected_by_admin = this_family_jobs.filter(job_taken=True).filter(job_done=True).filter(job_rejected_by_admin = True).order_by('-id')
        my_jobs_review_rejected_by_admin = this_family_jobs.filter(job_taker=user).filter(job_taken=True).filter(job_done=True).filter(job_rejected_by_admin = True).order_by('-id')
        jobs_paid = this_family_jobs.filter(job_taken=True).filter(job_done=True).filter(job_passed_review= True).filter(job_paid=True).order_by('-id')
        

        job_list = this_family_jobs.filter(job_taken= False).order_by('-id')
        job_gone = this_family_jobs.filter(job_taken= True).order_by('-id')
        my_unfinished_jobs = this_family_jobs.filter(job_taker=user).filter(job_taken=True).filter(job_done=False).order_by('-id')
        all_unfinished_jobs = this_family_jobs.filter(job_taken=True).filter(job_done=False).order_by('-id')

        my_done_jobs = this_family_jobs.filter(job_taker=user).filter(job_done=True).order_by('-id')
        all_done_jobs = this_family_jobs.filter(job_taken=True).filter(job_done=True).order_by('-id')
        my_money_under_review_this_month = this_family_jobs.filter(job_taken=True).filter(job_under_review= True).filter(job_done=True).aggregate(Sum('job_price'))
        my_total_this_mont = this_family_jobs.filter(job_taken=True).filter(job_done=True).filter(job_passed_review= True).aggregate(Sum('job_price'))
        unclaimed = this_family_jobs.filter(job_taken= False).aggregate(Sum('job_price'))

    else:
        print("I am not a staff")
        my_jobs_under_review = this_family_jobs.filter(job_taker=user).filter(job_taken= True).filter(job_under_review= True).order_by('-id')
        my_jobs_acceptably_done = this_family_jobs.filter(job_taker=user).filter(job_taken=True).filter(job_done=True).filter(job_passed_review= True).filter(job_paid=False).order_by('-id')
        jobs_under_review = this_family_jobs.filter(job_taken= True).filter(job_under_review= True).order_by('-id') 
        jobs_acceptably_done = this_family_jobs.filter(job_taken=True).filter(job_done=True).filter(job_passed_review= True).order_by('-id')
        jobs_paid = this_family_jobs.filter(job_taken=True).filter(job_taker=user).filter(job_done=True).filter(job_passed_review= True).filter(job_paid=True).order_by('-id')
        
        job_list = this_family_jobs_today.filter(job_taken= False).order_by('-id')         
        job_gone = this_family_jobs.filter(job_taken= True).order_by('-id')
        my_unfinished_jobs = this_family_jobs.filter(job_taker=user).filter(job_taken=True).filter(job_done=False).order_by('-id')
        all_unfinished_jobs = this_family_jobs_today.filter(job_taken=True).filter(job_done=False).order_by('-id')
        my_done_jobs = this_family_jobs.filter(job_taker=user).filter(job_done=True).order_by('-id')
        all_done_jobs = this_family_jobs.filter(job_taken=True).filter(job_done=True).order_by('-id')
        
        my_money_under_review_this_month = this_family_jobs.filter(job_taker=user).filter(job_taken=True).filter(job_under_review= True).filter(job_done=True).aggregate(Sum('job_price'))
        my_total_this_mont = this_family_jobs.filter(job_taker=user).filter(job_taken=True).filter(job_done=True).filter(job_passed_review= True).aggregate(Sum('job_price'))
        unclaimed = this_family_jobs_today.filter(job_taken= False).aggregate(Sum('job_price'))
        my_jobs_review_rejected_by_admin = this_family_jobs.filter(job_taker=user).filter(job_taken=True).filter(job_done=True).filter(job_rejected_by_admin = True).order_by('-id')
        jobs_review_rejected_by_admin = this_family_jobs.filter(job_taken=True).filter(job_done=True).filter(job_rejected_by_admin = True).order_by('-id')

    
    template = loader.get_template('jobs/index.html')
    print("Money", my_money_under_review_this_month)
    
    if request.user == 'AnonymousUser':
        usr = "None"
    else:
        usr = request.user
    context = {
     'job_list': job_list,
     'job_gone' : job_gone,
     'my_unfinished_jobs' : my_unfinished_jobs,
     'my_done_jobs' : my_done_jobs,
     'user': usr,
     'my_money_under_review_this_month':my_money_under_review_this_month,
     'my_total_this_mont': my_total_this_mont,
     'unclaimed': unclaimed,
     'all_unfinished_jobs' : all_unfinished_jobs,
     'all_done_jobs' : all_done_jobs,
     'jobs_acceptably_done' : jobs_acceptably_done,
     'jobs_under_review' : jobs_under_review,
     'my_jobs_acceptably_done' : my_jobs_acceptably_done,
     'my_jobs_under_review' : my_jobs_under_review,
     'date_today' : timezone.datetime.now(),
     'jobs_review_rejected_by_admin' : jobs_review_rejected_by_admin,
     'my_jobs_review_rejected_by_admin' : my_jobs_review_rejected_by_admin,
     'jobs_paid' : jobs_paid,
     

     }
    return HttpResponse(template.render(context, request))


@login_required
def detail(request, pk):
    print(pk)
    detail = get_object_or_404(JobPost, pk=pk) 
    template = loader.get_template('jobs/detail.html')
    if request.user == 'AnonymousUser':
        usr = "None"
    else:
        usr = request.user
    context = {
    'detail': detail,
    'user': usr,
    # 'my_money_under_review_this_month': my_money_under_review_this_month,
    # 'unclaimed': unclaimed,
    # 'my_total_this_mont': my_total_this_mont,
     }
    return HttpResponse(template.render(context, request))

def payments(request):
    
    user = User.objects.get(username = request.user)
    
    print(request.user, user.id)
    # if request.user.is_superuser:       
    #     job_list = JobPost.objects.filter(job_taken= False).order_by('-id') 
    #     job_gone = JobPost.objects.filter(job_taken= True).order_by('-id')
    # else:
    #     job_list = JobPost.objects.filter(job_taker = user_id).order_by('-id') 
    #     job_gone = JobPost.objects.filter(job_taken= True).order_by('-id')
    try:
        pk=request.POST['Choice']
        print("choice id : ", pk)
        upd_rec = JobPost.objects.get(pk=pk)
        upd_rec.job_taken = True
        upd_rec.job_taken_date = timezone.now()
        upd_rec.job_taker = user
        upd_rec.save()
    except Exception as e:
        print(e)
        
    payment_list = JobPost.objects.filter(job_taken= True).filter(job_done= False).order_by('-id') 
    template = loader.get_template('jobs/payments.html')

jobs/templates/jobs/dashboard.html
{% extends "jobs/base.html" %} {% load static %} {% block user %} {{user.first_name}} {{user.last_name}} {% endblock user %} {% block content %}
<div class=" container">
    {% if user.is_staff %}
    <div class="container bg-light p-2 m-2">
        <div class="row">
            <h5 id="mykids" class="mb-4 mt-1 ms-1 text-black-50 ps-4">My family</h5>
            {% for key, value in jobs_ready_for_payment_this_month.items %}
            <div class="col-6">
                <div class="card shadow mb-3">
                    <div class="card-header text-light bg-success">
                        <h5>{{key.first_name}} {{key.last_name}} </h5>
                    </div>
                    <div class="card-body text-black-50">
                        <div class="d-flex">
                            {% if value.job_price__sum == None %}
                            <p class="mt-1"><span class="fw-bold"> {{date_today|date:'F Y' }}</span> earnings :&nbsp;&nbsp;&nbsp; $0</p>
                            {% else %}
                            <p class="mt-1"><span class="fw-bold">{{ date_today|date:'F Y' }}</span> earnings :&nbsp;&nbsp;&nbsp; ${{value.job_price__sum}}</p>
                            {% endif %}


                            <div class="text-start">
                                {% if value.job_price__sum != None %}

                                <form class="text-center rounded-bottom" action="{% url 'jobs:job_payments' %}" method='post'>
                                    {% csrf_token %}

                                    <input type="radio" id="accept" name="Choice" value="{{key.id}}" checked style="display: none;">
                                    <label for="accept" style="display: none;"> Pay Now</label>
                                    <input type="submit" value="Pay Now" class="btn btn-success text-white fs-6 ms-3">
                                </form>

                                {% endif %}
                            </div>
                        </div>


                    </div>
                </div>

            </div>
            {% endfor %}
        </div>
    </div>



    <div class="container bg-light p-2 m-2 mt-4">
        <div class="row">

            <h5 id="mykidspayments" class="mb-4 mt-1 ms-1 text-black-50 ps-4">Payment history</h5>
            {% for key, value in payment_history.items %}
            <div class="col-6">
                <div class="card shadow mb-3">
                    <div class="card-header text-light bg-success">
                        <h5>{{key.first_name}} {{key.last_name}} </h5>
                    </div>
                    <div class="card-body text-black-50 p-0">
                        <div class="d-flex shadow-sm ps-3">
                            <div class="d-flex align-items-center">
                                <p class="p-0 ps-1 my-1">Payment ID</p>
                            </div>
                            <div class="d-flex align-items-center mx-5 ps-3">
                                <p class="p-0 ps-1 my-1">Payment Date</p>
                            </div>
                            <div class="d-flex align-items-center ms-5">
                                <p class="p-0 ps-1 my-1">Payment Amount</p>
                            </div>
                        </div>
                        {% for key, val in value.items %}
                        <div class="d-flex shadow-sm">
                            <div class="d-flex align-items-center ps-3">
                                <p class="p-0 ps-1 my-1">{{val.id}}</p>
                            </div>
                            <div class="d-flex align-items-center mx-5 ps-3">
                                <p class="p-0 ps-1 my-1">&nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {{val.payment_date.date}}</p>
                            </div>
                            <div class="d-flex align-items-center ms-5">
                                <p class="p-0 ps-1 my-1">&nbsp; ${{val.payment_amount}}</p>
                            </div>
                        </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="container bg-light p-2 m-2 mt-4">
        <h5 class="mt-4 mb-4 pt-3 text-black-50 ps-4">Job list</h5>
        <div class="row justify-content-start flex-wrap">

            {% if job_list %} {% for q in job_list %}
            <div class="card ms-4 mb-3 shadow rounded p-0" style="width: 12rem;">
                <a class="btn p-0" href="{% url 'jobs:detail' q.id%}" style="width: 100%;">
                    <div class="card-body p-0">
                        <div class="d-flex justify-content-between">
                            <small class="card-text text-black-50 mt-1 ms-1">{{q.publish_date.date}}</small>
                            <h3 class="text-danger mt-1 me-1 "><small>$</small>{{q.job_price}}</h3>
                        </div>
                        <h5 class="card-title pb-3 text-center text-black-50">{{ q.job_title }}</h5>
                        <!-- <p class="text-dark">{{q.job_detail}}</p> -->
                </a>
                </div>
            </div>
            {% endfor %} {% else %}

            <div class="card ms-4 mb-3 shadow bg-body rounded p-0" style="width: 12rem;">

                <div class="card-body mt-2 pb-0">
                    <p class="card-title pb-3 text-center text-black-50">No jobs available</p>
                </div>
            </div>
            {% endif %}

        </div>

    </div>



    <!-- ------- end admin --------- -->
    {% else %}

    <div class="container  p-2 m-2">
        <div class="row">
            <p>{{date_today.date}}</p>

            <div class="col">
                <div class="card shadow">
                    <div class="card-header">Today</div>
                    <div class="card-body">
                        {% if my_total_this_day.job_price__sum == None %}
                        <p>Total money earned : $0</p>
                        {% else %}
                        <p>Total money earned : ${{my_total_this_day.job_price__sum}}</p>
                        {% endif %} {% if unclaimed_this_day.job_price__sum == None %}
                        <p>Total money missed : $0</p>
                        {% else %}
                        <p>Total money missed : ${{unclaimed_this_day.job_price__sum}}</p>
                        {% endif %}

                    </div>
                    <div class="card-footer"></div>
                </div>

            </div>
            <div class="col">
                <div class="card shadow">
                    <div class="card-header">This Month</div>
                    <div class="card-body">
                        {% if my_total_this_month.job_price__sum == None %}
                        <p>Total money earned : $0</p>
                        {% else %}
                        <p>Total money earned : ${{my_total_this_month.job_price__sum}}</p>
                        {% endif %} {% if unclaimed_this_month.job_price__sum == None %}
                        <p>Total money missed : $0</p>
                        {% else %}
                        <p>Total money missed : ${{unclaimed_this_month.job_price__sum}}</p>
                        {% endif %}

                    </div>
                    <div class="card-footer"></div>
                </div>

            </div>
            <div class="col">
                <div class="card shadow">
                    <div class="card-header">This Year</div>
                    <div class="card-body">
                        {% if my_total_this_year.job_price__sum == None %}
                        <p>Total money earned : $0</p>
                        {% else %}
                        <p>Total money earned : ${{my_total_this_year.job_price__sum}}</p>
                        {% endif %} {% if unclaimed_this_year.job_price__sum == None %}
                        <p>Total money missed : $0</p>
                        {% else %}
                        <p>Total money missed : ${{unclaimed_this_year.job_price__sum}}</p>
                        {% endif %}
                    </div>
                    <div class="card-footer"></div>
                </div>

            </div>




        </div>



    </div>
</div>
{% endif %} {% endblock content %} {% block sidebar %}
<!-- <div class="col"> -->

<div class="d-flex flex-row ">
    <div class="d-flex flex-row ">

        {% if user.is_staff %}
        <div class=" mt-2 mb-2 text-center align-content-center border-start shadow-sm">
            <a class="btn p-0" href="../admin/" style="width: 100%;">
                <div class="" style="width: 150px;">

                    <img class="m-2" src="{% static 'jobs/admin.png'%}" style="width: 36px; height: 36px;" alt="Card image">
                    <div class="">
                        <p class="m-0 text-black-50 fs-6">Admin Access</p>

                        <form id="3" class="m-0 p-0" action="{% url 'jobs:mark_not_done' %}" method='post'>
                            {% csrf_token %}
                            <input type="radio" id="accept2" name="Choice" value=0 checked style="display: none;">
                            <label for="accept2" style="display: none; "> Reset Jobs</label>


                            <input type="submit" value="Reset Jobs" class="btn text-success m-0 p-0">
                        </form>


                    </div>
                </div>

            </a>
        </div>
        <div class=" mt-2 mb-2  text-center border-start shadow-sm">
            <a class="btn p-0" style="width: 100%;" href="{% url 'jobs:add_user' %}">
                <div class="" style="width: 150px;">
                    <img class="m-2" src="{% static 'jobs/new_user.png' %}" style="width: 36px; height: 36px;" alt="Card image">
                    <div class="">
                        <p class="m-0 text-black-50 fs-6">Add User</p>
                        <i class="btn text-black-50 fs-6">&nbsp;</i>
                    </div>
                </div>
            </a>


        </div>


        <div class=" mt-2 mb-2  text-center border-start shadow-sm">
            <a class="btn p-0" style="width: 100%;" href="{% url 'jobs:new_job' %}">
                <div class="" style="width: 150px;">
                    <img class="m-2" src="{% static 'jobs/new_job.png' %}" style="width: 36px; height: 36px;" alt="Card image">
                    <div class="">
                        <p class="m-0 text-black-50 fs-6">New Jobs</p>
                        <i class="btn text-black-50 fs-6">&nbsp;</i>
                    </div>
                </div>
            </a>


        </div>
        {% endif %}
        <div class=" mt-2 mb-2  text-center border-start shadow-sm">
            <a class="btn p-0" style="width: 100%;" href="/">
                <div class="" style="width: 150px;">
                    <img class="m-2" src="{% static 'jobs/home.png' %}" style="width: 36px; height: 36px;" alt="Card image">
                    <div class="">
                        <p class="m-0 text-black-50 fs-6">Home</p>
                        <i class="btn text-black-50 fs-6">&nbsp;</i>
                    </div>
                </div>
            </a>


        </div>

    </div>
</div>


{% endblock sidebar %}

jobs/templates/jobs/new_job.html
{% extends "jobs/base.html" %} {% load static %}{% block user %} {{user.first_name}} {{user.last_name}} {% endblock user %} {% block detail %}


<div class="container bg-light">
<div class="row mt-5">
    <div class="col"></div>
    <div class="col-6 p-3 text-black-50">
    <h5> Add new job </h5>
        <form method="POST" class="post-form">
            {% csrf_token %}
            <div class="card shadow pb-3">
                <div class="card-title bg-light p-2 text-black-50">
                    <h5>New job</h5>
                </div>
                <div class="card-body text-black-50">
                    <div class="row">
                        <div class="col">
                            <p class="p-0">Job title :&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; {{form.job_title}}</p>
                            <p class="p-0">Job detail : &nbsp;&nbsp;&nbsp; {{form.job_detail}}</p>
                            <p class="p-0">Job price : &nbsp;&nbsp;$ {{form.job_price}}</p>
                        </div>
                    </div>
                </div>
                <div class="text-center ">

                    <button type="submit" class="save btn btn-success w-75">Save</button>
        </form>
        </div>


        </div>


    </div>
    <div class="col"></div>
</div>
</div>


{% endblock detail %} {% block sidebar %}

<div class="d-flex flex-row ">
    <div class="d-flex flex-row ">

        {% if user.is_staff %}
        <div class=" mt-2 mb-2 text-center align-content-center border-start shadow-sm">
            <a class="btn p-0" href="../admin/" style="width: 100%;">
                <div class="" style="width: 150px;">
                    <img class="m-2" src="{% static 'jobs/admin.png'%}" style="width: 36px; height: 36px;" alt="Card image">
                    <div class="">
                        <p class="m-0 text-black-50 fs-6">Admin Access</p>
                        <form id="3" class="m-0 p-0" action="{% url 'jobs:mark_not_done' %}" method='post'>
                            {% csrf_token %}
                            <input type="radio" id="accept2" name="Choice" value=0 checked style="display: none;">
                            <label for="accept2" style="display: none;"> Reset Jobs</label>
                            <input type="submit" value="Reset Jobs" class="btn text-success m-0 p-0">
                        </form>
                    </div>
                </div>
            </a>
        </div>


        <div class=" mt-2 mb-2  text-center border-start shadow-sm">
            <a class="btn p-0" style="width: 100%;" href="{% url 'jobs:new_job' %}">
                <div class="" style="width: 150px;">
                    <img class="m-2" src="{% static 'jobs/new_job.png' %}" style="width: 36px; height: 36px;" alt="Card image">
                    <div class="">
                        <p class="m-0 text-black-50 fs-6">Add new job</p>
                        <i class="btn text-black-50 fs-6">&nbsp;</i>
                    </div>
                </div>
            </a>


        </div>
        {% endif %}
        <div class=" mt-2 mb-2  text-center border-start shadow-sm">
            <a class="btn p-0" style="width: 100%;" href="{% url 'jobs:dashboard' %}">
                <div class="" style="width: 150px;">
                    <img class="m-2" src="{% static 'jobs/dashboard.png' %}" style="width: 36px; height: 36px;" alt="Card image">
                    <div class="">
                        <p class="m-0 text-black-50 fs-6">My Dashboard</p>
                        <i class="btn text-black-50 fs-6">&nbsp;</i>
                    </div>
                </div>
            </a>


        </div>

    </div>
</div>

{% endblock sidebar %}

jobs/templates/jobs/payments.html
{% extends "jobs/base.html" %}
{% block user %}
<strong>{{user}}</strong> {% endblock user %} 
{% block content %}
<h3>Unfinished jobs for {{user}}</h3> 
    {% if payment_list %}
    {% comment %} {{payment_list.values}}  {% endcomment %}
    {% for q in payment_list %}
   
<div class="card mb-4 " style="width: 18rem;">
        
    <div class="card-body">
        {{q.id}}
        <small class="card-text">{{q.publish_date}}</small>
        <h3 class="card-title">{{ q.job_title }}</h3> 
        <p>{{q.job_detail}}</p>
        <p>${{q.job_price}}</p>
        <form action="{% url 'jobs:mark_done' %}" method='post'>
            {% csrf_token %}
            <p> Select your choice for this job</p>
            
            <input type="radio" id="accept" name="Choice" value={{q.id}}>
            <label for="accept"> Mark Done</label>
            <input type="radio" id="reject" name="Choice" value=-{{q.id}}>
            <label for="reject"> Can't Do Job</label>
            
            <input type="submit" value="Submit" class="btn btn-success">
    
    {% comment %} <a href="{% url 'jobs:index'%}" class="btn btn-success">Mark as done</a>
    <a href="{% url 'jobs:index'%}" class="btn btn-danger">Quit this job</a> {% endcomment %}


  </div>
          {% endfor %}
    {% else %}
    <div class="card-body">
        <h2 class="card-title">No data available.</h2>
        </div>
    {% endif %}

</div>
{% endblock content %}